app:
  model:
    user:
      name_max_length: 50
      email_max_length: 255
      pass_max_length: 6
      gravatar_size: 80
      time_expired_reset: 2
  yes_remmeber: "1"
  page_user:
    per_page: 20
    size_avatar: 50
  micropost:
    image_accept: "image/jpeg,image/gif,image/png"
    image_size_mb: 5
    content_length: 140
    
